---
- hosts: all
  gather_facts: False
  vars:
      timestamp: '{{arguments["timestamp"]|dateFormat("%d %b %Y %H:%M:%S","%Y\\/%m\\/%d %H")}}'
      valid_urls:
          - public
          - webpickle
          - jar
          - accounts
          - api
            #update with your list of relevant top-level routes for your app
  
  tasks:
  - name: get the base url of the request
    shell: sed -n -e  '/{{timestamp}}/,$p' /var/log/nginx/error.log | awk -F \" '{print $4}' | awk '{print $2}' | awk -F / '{print $2}'
    register: req_urls

  - name: check if errored out routes are valid ones
    picklebot: resolve
    when: valid_routes|intersect(req_urls.stdout_lines)|count == 0 

  - name: get the log content from the time of alert
    shell: sed -n -e  '/{{timestamp}}/,$p' /var/log/nginx/error.log
    register: log_content
    when: valid_routes|intersect(req_urls.stdout_lines)|count != 0 

  - name: add the log content from the time of alert to the incident note
    picklebot: note={{log_content.stdout}}
    when: valid_routes|intersect(req_urls.stdout_lines)|count != 0 


